apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: manehharutyunyan/devops-backend:latest 
          ports:
            - containerPort: 80
          env:
          - name: DB_ENDPOINT
            valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: var2-key 
